export const REQUEST_SIGNIN_PENDING = 'REQUEST_SIGNIN_PENDING';
export const REQUEST_SIGNIN_SUCCESS = 'REQUEST_SIGNIN_SUCCESS';
export const REQUEST_SIGNIN_FAILED = 'REQUEST_SIGNIN_FAILED';

export const REQUEST_FILMLIST_PENDING = 'REQUEST_FILMLIST_PENDING';
export const REQUEST_FILMLIST_SUCCESS = 'REQUEST_FILMLIST_SUCCESS';
export const REQUEST_FILMLIST_FAILED = 'REQUEST_FILMLIST_FAILED';

export const SET_USER = "SET_USER";